name: Docker CI Workflow
on:
  release:
    types: [created]
  push:
    branches:
      - '**'

jobs:
  call-docker-ci-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/docker-ci.yml@v3
    with:
      name: qubership-apihub-build-task-consumer
      file: Dockerfile
      context: ""
      platforms: linux/amd64,linux/arm64
    secrets:
      NPMRC: ${{ secrets.NPMRC }}
